### ISSUE TITLE
安装之后需要登陆itunes  之后闪退

### ISSUE THREAD

**Issue by swwios12369** [Virtue86/Shadowrocket---iOS-ipa#2]

**Comment by Virtue86** [comment]
这种情况，只能去win平台的xx助手去下载了。

**Comment by uiuco** [comment]
我这边是，iPhone7安装之后是成功的，但是iPhoneX & iPad需要登录iTunes之后闪退

**Comment by Virtue86** [comment]
> 我这边是，iPhone7安装之后是成功的，但是iPhoneX & iPad需要登录iTunes之后闪退

试着修改一下appleid的密码

**Comment by vbonluk** [comment]
iPhone x，repeat this problem

**Comment by zealzhangz** [comment]
Iphone8 安装后输入密码闪退

**Comment by CHUZHIYUAN** [comment]
iPhone X open crash？How to solve this problem?

**Comment by hccgk** [comment]
一样不输入appid 直接退  输入了 闪退，这个怎么破？

**Comment by Virtue86** [comment]
> 一样不输入appid 直接退 输入了 闪退，这个怎么破？

现在手机越狱或者不是大陆版本的可以使用了。

**Comment by hccgk** [comment]
> > 一样不输入appid 直接退 输入了 闪退，这个怎么破？
> 
> 现在手机越狱或者不是大陆版本的可以使用了。

谢谢，后来找了个已购买的账号下载了

**Comment by guoyongxin** [comment]
必须是付费开发者账号才可以吧？

**Comment by Virtue86** [comment]
如果只是单纯使用 VPN，请申请一个非大陆 appleid 进行下载吧，谢谢！
