### ISSUE TITLE
会闪退啊！

### ISSUE THREAD

**Issue by ineyko** [Virtue86/Shadowrocket---iOS-ipa#3]

**Comment by Virtue86** [comment]
如果之前没有使用apple id 购买会闪退的

**Comment by KingZh** [comment]
最近我这也出现闪退的情况了，没有visa卡绑定美区的apple id，无法购买啊，怎么办

**Comment by ineyko** [comment]
之前的apple id 确实没买过，后来找到个办法，下载ipa文件再通过爱思助手或者pp助手这样的软件安装就不闪退了。完美解决。

**Comment by KingZh** [comment]
> 之前的apple id 确实没买过，后来找到个办法，下载ipa文件再通过爱思助手或者pp助手这样的软件安装就不闪退了。完美解决。

我通过这个方式安装上了但也是闪退，不知道为什么，13.2的系统
